packages:
 - !include openamber/common/openamber.yaml

substitutions:
  device_model: leejow

esp32:
  board: esp32dev
  framework:
    advanced:
      minimum_chip_revision: "3.1"

esphome:
 project:
  version: dev
    
modbus:
  flow_control_pin: GPIO14

uart:
  rx_pin: GPIO32
  tx_pin: GPIO33

switch:
 - platform: gpio
   pin: GPIO22
   name: "Relais verwarming"
   id: relay_heating
   icon: mdi:electric-switch
   restore_mode: RESTORE_DEFAULT_OFF
   web_server: 
    sorting_group_id: manual_control

 - platform: gpio
   pin: GPIO23
   name: "Relais koelen"
   id: relay_cooling
   icon: mdi:electric-switch
   restore_mode: RESTORE_DEFAULT_OFF
   web_server: 
    sorting_group_id: manual_control

sensor:
  - platform: pulse_counter
    pin: GPIO35
    name: Pulse meter
    id: water_flow_rate
    device_class: volume_flow_rate
    unit_of_measurement: L/min
    filters:
      - lambda: return (x / id(flow_sensor_calibration).state);
    total:
      name: Total pulses
      disabled_by_default: true
      unit_of_measurement: l
      filters:
        - lambda: return x / id(flow_sensor_calibration).state;
        - delta: 1
