sensor: !include sensor_ui_bindings.yaml
number: !include number_ui_bindings.yaml
binary_sensor: !include binary_sensor_ui_bindings.yaml
select: !include select_ui_bindings.yaml
switch: !include switch_ui_bindings.yaml
text_sensor: !include text_sensor_ui_bindings.yaml
script: !include script_ui_bindings.yaml