- platform: template
  id: backup_heating_mode
  name: "Backup verwarmingsmodus"
  optimistic: True
  options:
    - "Intern verwarmingselement"
    - "Externe backup verwarming"
  initial_option: "Intern verwarmingselement"
  restore_value: True
  entity_category: config
  web_server: 
    sorting_group_id: heating_settings

- platform: template
  id: heat_compressor_mode
  name: "Verwarmen vermogen"
  restore_value: True
  optimistic: True
  options:
    - "Beperkt"
    - "Zeer laag"
    - "Laag"
    - "Gemiddeld"
    - "Verhoogd"
    - "Hoog"
    - "Maximaal"
  initial_option: "Maximaal"
  entity_category: config
  web_server: 
      sorting_group_id: heating_settings

- platform: template
  id: cool_compressor_mode
  name: "Koelen vermogen"
  restore_value: True
  optimistic: True
  options:
    - "Beperkt"
    - "Zeer laag"
    - "Laag"
    - "Gemiddeld"
    - "Verhoogd"
    - "Hoog"
    - "Maximaal"
  initial_option: "Maximaal"
  entity_category: config
  web_server: 
      sorting_group_id: cooling_settings

- platform: template
  id: dhw_compressor_mode
  name: "Tapwater basisvermogen"
  restore_value: True
  optimistic: True
  options:
    - "Beperkt"
    - "Zeer laag"
    - "Laag"
    - "Gemiddeld"
    - "Verhoogd"
    - "Hoog"
    - "Maximaal"
  initial_option: "Beperkt"
  entity_category: config
  web_server: 
      sorting_group_id: dhw_settings

- platform: template
  id: dhw_compressor_mode_max
  name: "Tapwater wintervermogen"
  restore_value: True
  optimistic: True
  options:
    - "Gemiddeld"
    - "Verhoogd"
    - "Hoog"
    - "Maximaal"
  initial_option: "Gemiddeld"
  entity_category: config
  web_server: 
      sorting_group_id: dhw_settings

- platform: template
  id: dhw_pump_start_mode_select
  name: "Tapwater pomp startmodus"
  optimistic: True
  restore_value: True
  options:
    - "Aanvoer warmer dan vat (ΔT)"
    - "Samen met compressor"
  initial_option: "Aanvoer warmer dan vat (ΔT)"
  entity_category: config
  web_server: 
      sorting_group_id: dhw_settings

- platform: template
  id: heat_mode_select
  name: "Verwarmingsmodus"
  optimistic: True
  options:
    - "Stooklijn"
    - "Extern setpoint"
  initial_option: "Stooklijn"
  restore_value: True
  entity_category: config
  web_server: 
    sorting_group_id: heating_settings
  on_value: 
    then:
      - component.update: current_setpoint

- platform: template
  id: heat_cool_control_temperature_source_select
  name: "Regeltemperatuur bron"
  optimistic: True
  options:
    - "CV-aanvoer (Tc)"
    - "CV-aanvoer zone 1 (Tv1)"
  initial_option: "CV-aanvoer (Tc)"
  restore_value: True
  entity_category: config
  web_server:
    sorting_group_id: heating_settings

- platform: template
  id: cool_mode_select
  name: "Koelmodus"
  optimistic: True
  options:
    - "Intern setpoint"
    - "Extern setpoint"
  initial_option: "Intern setpoint"
  restore_value: True
  entity_category: config
  web_server: 
    sorting_group_id: cooling_settings
  on_value: 
    then:
      - component.update: current_setpoint

- platform: template
  id: thermostat_mode_select
  name: "Thermostaat keuze"
  optimistic: True
  options:
    - "Intern"
    - "Extern"
  initial_option: "Extern"
  restore_value: True
  entity_category: config
  web_server: 
    sorting_group_id: heating_settings

- platform: template
  id: sg_ready_mode_select
  name: "SG-Ready modus"
  optimistic: True
  options:
    - "Normaal"
    - "Blokkeren"
    - "Boost"
    - "Max boost"
  initial_option: "Normaal"
  restore_value: True
  entity_category: config
  web_server: 
    sorting_group_id: manual_control

- platform: logger
  name: "Logging niveau"

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  id: compressor_control_select
  name: "Compressor stand (Buiten)"
  internal: True
  address: 1999
  value_type: S_WORD
  web_server:
    sorting_group_id: manual_control
  optionsmap:
    "0": 0
    "1": 1
    "2": 2
    "3": 3
    "4": 4
    "5": 5
    "6": 6
    "7": 7
    "8": 8
    "9": 9
    "10": 10
- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  id: working_mode_switch
  internal: True
  name: "Bedrijfsmodus"
  address: 3999
  on_value: 
    then:
      - lambda: 
          id(modbus_outside_is_online) = true;
      - component.update: current_setpoint
  optionsmap:
    "Standby": 0
    "Koelen": 1
    "Verwarmen": 2
    "Onderhoud": 6

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  id: bottomplate_heater_mode
  name: "Bodemplaat verwarmingsmodus"
  address: 3236
  optionsmap:
    "Onbekend": 0
    "Buitentemperatuur": 1
    "Tijdens defrost": 2