- platform: template
  id: pump_p1_enabled
  name: "Pomp P1 aanwezig"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: heating_settings

- platform: template
  id: pump_p0_pid_enabled
  name: "Pomp P0 PID regeling"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server:
    sorting_group_id: heating_settings

- platform: template
  id: legio_enabled_switch
  name: "Legionellapreventie"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_settings

- platform: template
  id: dhw_enabled_switch
  name: "Tapwater aanwezig"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_settings

- platform: template
  id: dhw_schedule_enabled_switch
  name: "Tapwater schema actief"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_schedule_settings

- platform: template
  id: dhw_schedule_monday_enabled_switch
  name: "Tapwater schema Maandag"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_schedule_settings

- platform: template
  id: dhw_schedule_tuesday_enabled_switch
  name: "Tapwater schema Dinsdag"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_schedule_settings

- platform: template
  id: dhw_schedule_wednesday_enabled_switch
  name: "Tapwater schema Woensdag"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_schedule_settings

- platform: template
  id: dhw_schedule_thursday_enabled_switch
  name: "Tapwater schema Donderdag"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_schedule_settings

- platform: template
  id: dhw_schedule_friday_enabled_switch
  name: "Tapwater schema Vrijdag"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_schedule_settings

- platform: template
  id: dhw_schedule_saturday_enabled_switch
  name: "Tapwater schema Zaterdag"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_schedule_settings

- platform: template
  id: dhw_schedule_sunday_enabled_switch
  name: "Tapwater schema Zondag"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server: 
    sorting_group_id: dhw_schedule_settings

- platform: template
  id: analytics_enabled_switch
  name: "Analytics versturen"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  setup_priority: 200
  web_server: 
    sorting_group_id: diagnostic
  on_state:
    then:
      - if:
          condition:
            - switch.is_on: analytics_enabled_switch
          then:
            - mqtt.enable:
          else:
            - mqtt.disable:

- platform: template
  id: advanced_settings_enabled
  name: "Geavanceerde instellingen"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server:
    sorting_group_id: general_settings

- platform: template
  id: service_mode_enabled
  name: "Onderhoudsmodus"
  optimistic: True
  entity_category: config
  disabled_by_default: true
  web_server:
    sorting_group_id: manual_control

- platform: template
  id: deaeration_short_switch
  name: "Ontluchting kort"
  entity_category: config
  disabled_by_default: true
  web_server:
    sorting_group_id: manual_control
  lambda: |-
    return id(amber_ctrl).is_deaeration_running() && !id(amber_ctrl).is_deaeration_extended();
  turn_on_action:
    - lambda: |-
        id(amber_ctrl).start_deaeration_routine(false);
  turn_off_action:
    - lambda: |-
        if (id(amber_ctrl).is_deaeration_running() && !id(amber_ctrl).is_deaeration_extended()) {
          id(amber_ctrl).stop_deaeration_routine();
        }

- platform: template
  id: deaeration_extended_switch
  name: "Ontluchting uitgebreid"
  entity_category: config
  disabled_by_default: true
  web_server:
    sorting_group_id: manual_control
  lambda: |-
    return id(amber_ctrl).is_deaeration_running() && id(amber_ctrl).is_deaeration_extended();
  turn_on_action:
    - lambda: |-
        id(amber_ctrl).start_deaeration_routine(true);
  turn_off_action:
    - lambda: |-
        if (id(amber_ctrl).is_deaeration_running() && id(amber_ctrl).is_deaeration_extended()) {
          id(amber_ctrl).stop_deaeration_routine();
        }

- platform: template
  id: flow_sensor_enabled
  name: "Flow sensor aanwezig"
  optimistic: True
  restore_mode: RESTORE_DEFAULT_OFF
  entity_category: config
  web_server:
    sorting_group_id: general_settings

- platform: template
  id: emergency_mode_enabled
  name: "Noodbedrijf"
  optimistic: True
  entity_category: config
  web_server:
    sorting_group_id: general_settings

- platform: template
  id: reset_start_timeout_errors_switch
  name: "Reset systeem timeout fouten"
  optimistic: true
  restore_mode: ALWAYS_OFF
  entity_category: diagnostic
  web_server:
    sorting_group_id: error_codes
  turn_on_action:
    - lambda: |-
        id(error_pump_start_timeout).publish_state(false);
        id(error_compressor_start_timeout).publish_state(false);
        id(error_pump_stop_timeout).publish_state(false);
        id(error_modbus_connection_timeout).publish_state(false);
        id(error_three_way_valve_state_timeout).publish_state(false);
    - switch.turn_off: reset_start_timeout_errors_switch

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  id: bottom_plate_heater_manual_switch
  name: "Bodemplaat verwarming handmatig"
  internal: True
  address: 2010
  register_type: holding
  bitmask: 0x4
  web_server:
    sorting_group_id: manual_control

- platform: modbus_controller
  modbus_controller_id: modbus_outside_unit
  id: compressor_crankcase_heater_manual_switch
  name: "Compressor carterverwarming handmatig"
  internal: True
  address: 2010
  register_type: holding
  bitmask: 0x8
  web_server:
    sorting_group_id: manual_control

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: pump_p0_relay_switch
  name: "Pomp P0 relais"
  internal: True
  address: 1099
  register_type: holding
    
- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: pump_p1_relay_switch
  name: "Pomp P1 relais"
  internal: True
  address: 1100
  register_type: holding

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: pump_p2_relay_switch
  name: "Pomp P2 relais"
  internal: True
  address: 1101
  register_type: holding

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: dhw_pump_relay_switch
  name: "Tapwater pomp relais"
  internal: True
  address: 1102
  register_type: holding
    
- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: initialize_relay_switch
  internal: True
  name: "Binnen unit relais onbekend"
  address: 1104
  register_type: holding

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: three_way_valve_heat_cool_switch
  name: "3-weg klep Koelen & Verwarmen"
  internal: True
  address: 1105
  register_type: holding

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: external_backup_heating_relay
  internal: True
  address: 1108
  register_type: holding

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: backup_heater_stage_1
  name: "Backup heater stage 1"
  internal: True
  address: 1109
  register_type: holding

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: backup_heater_stage_2
  name: "Backup heater stage 2"
  internal: True
  address: 1110
  register_type: holding

- platform: modbus_controller
  modbus_controller_id: modbus_inside_unit
  id: three_way_valve_dhw_switch
  name: "3-weg klep SWW"
  internal: True
  address: 1112
  register_type: holding

- platform: template
  optimistic: True
  id: backup_heater_relay
  name: "Backup verwarmingselement"
  internal: True
  on_state: 
    then:
    - switch.control:
        id: backup_heater_stage_1
        state: !lambda return x;
    - switch.control:
        id: backup_heater_stage_2
        state: !lambda return x;

- platform: template
  id: heat_demand_switch
  name: "Externe warmtevraag"
  optimistic: True
  web_server: 
    sorting_group_id: manual_control

- platform: template
  id: cool_demand_switch
  name: "Externe koudevraag"
  optimistic: True
  web_server: 
    sorting_group_id: manual_control